---
title: "Processing Raw miRNA Counts"
author: "Benji Lamp"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, message=F}
library(readr)
library(DESeq2)
library(here)
```

## Load natasha's Raw Counts
```{r}
# Read the CSV file
file_path <- 'https://raw.githubusercontent.com/blamp23/transcriptional_dynamics_of_bov_mam/main/miRNA/raw_data/mirna_raw_counts.csv'
df <- read.csv(file_path)
row.names(df) <- df$X
df <- df[-1]
df <- t(df)
```

## Create metadata 
```{r}
samples <- data.frame(
  row.names = c(colnames(df)),
  condition = c((substr(colnames(df), 5, nchar(colnames(df)))))
)

head(samples)
```

## Run create deseq object and pull norm counts
```{r, message=FALSE, warning=FALSE}
df <- as.matrix(df)
head(df)
dds <- DESeqDataSetFromMatrix(
  countData = df,
  colData = samples,
  design = ~ condition
)

dds <- DESeq(dds)

normalized_counts <- counts(dds, normalized = TRUE)

head(normalized_counts)
```


# Save Image
```{r}
x <- ls()
x <- x[!x %in% c("dds", "normalized_counts")]
rm(list = x)
rm(x)

save.image(here("miRNA/processed_data", "miRNA_deseq_results.RData"))
```


